"""auditoria administrativa

Revision ID: 0f8fc9122d84
Revises: b1c4f2a97d31
Create Date: 2026-08-22 23:18:09.016992
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0f8fc9122d84"
down_revision: str | None = "b1c4f2a97d31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_reviews",
        sa.Column("purchase_id", sa.UUID(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["lead_purchases.id"],
            name=op.f("fk_purchase_reviews_purchase_id_lead_purchases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_purchase_reviews_reviewed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_reviews")),
    )
    op.create_index(
        "ix_purchase_reviews_purchase",
        "purchase_reviews",
        ["purchase_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "lead_consents", sa.Column("external_channel", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "lead_consents",
        sa.Column("external_campaign_reference", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lead_consents", "external_campaign_reference")
    op.drop_column("lead_consents", "external_channel")
    op.drop_index("ix_purchase_reviews_purchase", table_name="purchase_reviews")
    op.drop_table("purchase_reviews")
    # ### end Alembic commands ###
