"""mensualidad configurable

Revision ID: 34c4e1084577
Revises: f74c49826ab1
Create Date: 2026-09-28 22:19:41.658092
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "34c4e1084577"
down_revision: str | None = "f74c49826ab1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_prices",
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=255), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_subscription_prices_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_subscription_prices_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_prices")),
        sa.UniqueConstraint("stripe_price_id", name=op.f("uq_subscription_prices_stripe_price_id")),
    )
    op.create_index(
        "ix_subscription_prices_created_at",
        "subscription_prices",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_subscription_prices_created_at", table_name="subscription_prices")
    op.drop_table("subscription_prices")
    # ### end Alembic commands ###
