"""feature flags por entorno

Revision ID: 4af940c8800c
Revises: df74f4157f5d
Create Date: 2026-10-05 10:11:13.456439
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4af940c8800c"
down_revision: str | None = "df74f4157f5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("environment", sa.Enum("dev", "prod", name="flag_environment"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "name ~ '^[a-z0-9][a-z0-9._-]*$'", name=op.f("ck_feature_flags_name_format")
        ),
        sa.CheckConstraint(
            "length(btrim(version)) > 0", name=op.f("ck_feature_flags_version_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
        sa.UniqueConstraint("name", "environment", name="uq_feature_flags_name_environment"),
        comment=(
            "Feature flags del frontend por entorno (dev/prod). Se cambian aqui a mano; "
            "la web tarda hasta 60 s en verlo. Una flag que falta cuenta como apagada."
        ),
    )
    # ### end Alembic commands ###

    # Las flags se cambian con SQL a mano: el `onupdate` del ORM no se entera, asi que
    # es Postgres quien mantiene `updated_at` (cuando se encendio o apago cada una).
    op.execute(
        """
        CREATE FUNCTION feature_flags_touch_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at := now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER feature_flags_updated_at
        BEFORE UPDATE ON feature_flags
        FOR EACH ROW EXECUTE FUNCTION feature_flags_touch_updated_at()
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # El trigger cae con la tabla; la funcion no.
    op.drop_table("feature_flags")
    op.execute("DROP FUNCTION IF EXISTS feature_flags_touch_updated_at()")
    # ### end Alembic commands ###
    # Los tipos ENUM no los borra drop_table: hay que hacerlo a mano o el
    # siguiente upgrade falla con 'type already exists'.
    for enum_name in ("flag_environment",):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
