"""recarga mensual y saldo

Revision ID: f74c49826ab1
Revises: 0f8fc9122d84
Create Date: 2026-09-28 21:05:44.028228
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f74c49826ab1"
down_revision: str | None = "0f8fc9122d84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professional_accounts",
        sa.Column("professional_id", sa.UUID(), nullable=False),
        sa.Column(
            "subscription_status",
            sa.Enum(
                "none", "pending", "active", "past_due", "canceled", name="subscription_status"
            ),
            nullable=False,
        ),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("balance_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balance_cents >= 0", name=op.f("ck_professional_accounts_balance_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professionals.id"],
            name=op.f("fk_professional_accounts_professional_id_professionals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("professional_id", name=op.f("pk_professional_accounts")),
        sa.UniqueConstraint(
            "stripe_customer_id", name=op.f("uq_professional_accounts_stripe_customer_id")
        ),
    )
    op.create_table(
        "credit_entries",
        sa.Column("professional_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "topup",
                "spend",
                "spend_reversal",
                "adjustment_credit",
                "adjustment_debit",
                name="credit_entry_kind",
            ),
            nullable=False,
        ),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_credit_entries_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_credit_entries_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_accounts.professional_id"],
            name=op.f("fk_credit_entries_professional_id_professional_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_entries")),
        sa.UniqueConstraint("kind", "source_ref", name="uq_credit_entries_kind_source_ref"),
    )
    op.create_index(
        "ix_credit_entries_professional",
        "credit_entries",
        ["professional_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.add_column(
        "lead_purchases",
        sa.Column(
            "credit_applied_cents", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.create_check_constraint(
        op.f("ck_lead_purchases_credit_applied_in_range"),
        "lead_purchases",
        "credit_applied_cents >= 0 AND credit_applied_cents <= amount_cents",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_lead_purchases_credit_applied_in_range"), "lead_purchases", type_="check"
    )
    op.drop_column("lead_purchases", "credit_applied_cents")
    op.drop_index("ix_credit_entries_professional", table_name="credit_entries")
    op.drop_table("credit_entries")
    op.drop_table("professional_accounts")
    # ### end Alembic commands ###
    # Los tipos ENUM no los borra drop_table: hay que hacerlo a mano o el
    # siguiente upgrade falla con 'type already exists'.
    for enum_name in ("credit_entry_kind", "subscription_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
